name: The Edge of the Inside
favicon: null
layout_spectrum: 0.6691787100862712
typography_spectrum: 0.9851544685661793
title: The Edge of the Inside
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8909745544660836
  lightness: 0.7994345338083804
  saturation: 0.10887155495584011
  rhythmicContrast: 0.6310969854239374
purpose: []
