name: The Edge of the Inside
favicon: null
layout_spectrum: 0.7478
typography_spectrum: 1
title: The Edge of the Inside
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#61371a'
    - '#c3b59d'
    - '#ae9b81'
    - '#7d5b3f'
    - '#47150c'
  brandStrength: 0.8909745544660836
  lightness: 0.7994345338083804
  saturation: 0.125
  rhythmicContrast: 0.6310969854239374
purpose: []
